version: '2'

services:
   travian:
      build: travian
      container_name: travian
      ports:
         - "8003:80"
      volumes:
         - ./appdata/TravianZ:/var/www/html
       command: /bin/bash -c "chown -R 33:33 /var/www/html && your_startup_command"

   mysql:
      image: "mysql:8.0.29-debian"
      container_name: travian-sql
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=travian
         - MYSQL_USER=travian
         - MYSQL_PASSWORD=travian
      volumes:
         - ./appdata/mysql/data:/var/lib/mysql
